# Generated by Django 3.2.4 on 2021-08-19 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0011_auto_20210819_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billNo', models.IntegerField(unique=True)),
                ('salesTaxInvoice', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=300)),
                ('byUs', models.FloatField(blank=True, null=True)),
                ('byYou', models.FloatField(blank=True, null=True)),
                ('grossTotal', models.FloatField(blank=True, null=True)),
                ('charges', models.FloatField(blank=True, null=True)),
                ('rateOfST', models.FloatField(blank=True, null=True)),
                ('salesTax', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('inwords', models.CharField(blank=True, max_length=500, null=True)),
                ('jobNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
        ),
    ]
