# Generated by Django 3.2.4 on 2021-08-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='reciept',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
