# Generated by Django 3.2.4 on 2021-08-28 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_job_deposit'),
        ('billing', '0002_bill_reciept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='byUs',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='byYou',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='reciept',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='title',
        ),
        migrations.CreateModel(
            name='Particular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('reciept', models.CharField(blank=True, max_length=150, null=True)),
                ('byUs', models.FloatField(blank=True, null=True)),
                ('byYou', models.FloatField(blank=True, null=True)),
                ('jobNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
        ),
    ]
