# Generated by Django 3.2.4 on 2021-09-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20210829_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='particular',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
