# Generated by Django 3.2.4 on 2021-09-05 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_particular_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='particular',
            name='jobNo',
        ),
        migrations.AddField(
            model_name='particular',
            name='billNo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='billing.bill'),
            preserve_default=False,
        ),
    ]
