# Generated by Django 3.2.4 on 2021-09-05 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_job_deposit'),
        ('billing', '0005_auto_20210906_0343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='particular',
            name='billNo',
        ),
        migrations.AddField(
            model_name='particular',
            name='jobNo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
            preserve_default=False,
        ),
    ]
