# Generated by Django 3.2.4 on 2021-09-05 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_auto_20210906_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='billNo',
            field=models.IntegerField(),
        ),
    ]
