# Generated by Django 3.2.4 on 2021-09-06 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_bill_billno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='particular',
            options={'ordering': ['jobNo']},
        ),
    ]
