# Generated by Django 3.2.4 on 2021-09-07 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_alter_particular_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='particular',
            options={'ordering': ['job']},
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='jobNo',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='particular',
            old_name='jobNo',
            new_name='job',
        ),
    ]
