# Generated by Django 3.2.6 on 2021-09-08 08:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_auto_20210907_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='billDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
