# Generated by Django 3.2.6 on 2021-09-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_bill_billdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='billDate',
            field=models.DateField(),
        ),
    ]
