# Generated by Django 3.2.4 on 2021-09-09 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_alter_bill_billdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='billDate',
        ),
    ]
