# Generated by Django 3.2.4 on 2021-09-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_remove_bill_billdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='cashNo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='gdNo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
