# Generated by Django 3.2.7 on 2021-09-29 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_pidbill_pidparticular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pidbill',
            name='charges',
        ),
        migrations.RemoveField(
            model_name='pidbill',
            name='grossTotal',
        ),
        migrations.RemoveField(
            model_name='pidbill',
            name='rateOfST',
        ),
        migrations.RemoveField(
            model_name='pidbill',
            name='salesTax',
        ),
        migrations.RemoveField(
            model_name='pidbill',
            name='total',
        ),
    ]
