# Generated by Django 3.2.7 on 2021-10-04 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_auto_20210929_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='header',
            options={'ordering': ['id']},
        ),
    ]
