# Generated by Django 3.2.4 on 2021-08-08 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('client', '0002_alter_client_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobNo', models.IntegerField()),
                ('jobDate', models.DateField()),
                ('packages', models.CharField(max_length=200)),
                ('vessel', models.CharField(max_length=200)),
                ('igm', models.IntegerField()),
                ('igmDate', models.DateField()),
                ('index', models.IntegerField()),
                ('lc', models.CharField(blank=True, max_length=200, null=True)),
                ('lcDate', models.DateField(blank=True, null=True)),
                ('bl', models.CharField(max_length=200)),
                ('blDate', models.DateField()),
                ('dv', models.FloatField(blank=True, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('exRate', models.FloatField(blank=True, null=True)),
                ('importValueUSD', models.FloatField(blank=True, null=True)),
                ('pkr', models.FloatField(blank=True, null=True)),
                ('insurance', models.FloatField(blank=True, null=True)),
                ('landingCharges', models.FloatField(blank=True, null=True)),
                ('importValue', models.FloatField(blank=True, null=True)),
                ('rateOfDuty', models.FloatField(blank=True, null=True)),
                ('customDuty', models.FloatField(blank=True, null=True)),
                ('rateOfAddDuty', models.FloatField(blank=True, null=True)),
                ('addCustomDuty', models.FloatField(blank=True, null=True)),
                ('rateOfST', models.FloatField(blank=True, null=True)),
                ('salesTax', models.FloatField(blank=True, null=True)),
                ('rateOfIT', models.FloatField(blank=True, null=True)),
                ('incomeTax', models.FloatField(blank=True, null=True)),
                ('excise', models.FloatField(blank=True, null=True)),
                ('terminal', models.FloatField(blank=True, null=True)),
                ('do', models.FloatField(blank=True, null=True)),
                ('lolo', models.FloatField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.item')),
            ],
        ),
    ]
