# Generated by Django 3.2.4 on 2021-08-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_jobdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='jobDate',
            field=models.DateField(),
        ),
    ]
