# Generated by Django 3.2.6 on 2021-08-12 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_lolo'),
        ('jobs', '0003_alter_job_jobdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.shippingline'),
        ),
        migrations.AlterField(
            model_name='job',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.terminal'),
        ),
    ]
