# Generated by Django 3.2.6 on 2021-08-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20210812_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='terminalCharges',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
