# Generated by Django 3.2.6 on 2021-08-12 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_lolo'),
        ('jobs', '0006_rename_lolo_job_lolocharges'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='lolo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.lolo'),
        ),
    ]
