# Generated by Django 3.2.4 on 2021-08-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_lolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='dutyType',
            field=models.CharField(blank=True, choices=[('%', '%'), ('F', 'F')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
