# Generated by Django 3.2.4 on 2021-08-12 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_lolo'),
        ('jobs', '0009_auto_20210812_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='addCustomDuty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='customDuty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='dutyType',
            field=models.CharField(blank=True, choices=[('%', '%'), ('F', 'F')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='excise',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='incomeTax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobNo',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='rateOfAddDuty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='rateOfDuty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='rateOfIT',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='rateOfST',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salesTax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='shipping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.shippingline'),
        ),
        migrations.AlterField(
            model_name='job',
            name='terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.terminal'),
        ),
        migrations.AlterField(
            model_name='job',
            name='terminalCharges',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='total',
            field=models.FloatField(),
        ),
    ]
