# Generated by Django 3.2.6 on 2021-08-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_auto_20210819_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='antiDumping',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='rateOfAD',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
