# Generated by Django 3.2.6 on 2021-08-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_auto_20210823_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='billed',
            field=models.BooleanField(default=False),
        ),
    ]
