# Generated by Django 3.2.6 on 2021-08-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_job_billed'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='deposit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
