# Generated by Django 3.2.7 on 2021-10-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_pid_faithcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='faithCheck',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
