# Generated by Django 3.2.7 on 2021-12-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_job_faithcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='advanceRent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
