# Generated by Django 3.2.7 on 2021-12-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_job_advancerent'),
    ]

    operations = [
        migrations.AddField(
            model_name='pid',
            name='advanceRent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
