# Generated by Django 3.2.7 on 2021-12-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_auto_20211221_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pid',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
