# Generated by Django 3.2.7 on 2022-01-11 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_auto_20220111_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pid',
            old_name='psqcTesting',
            new_name='psqcaTesting',
        ),
    ]
