# Generated by Django 3.2.7 on 2022-01-11 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0027_rename_psqctesting_pid_psqcatesting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='psqcTesting',
            new_name='psqcaTesting',
        ),
    ]
