# Generated by Django 3.2.7 on 2022-01-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_rename_psqctesting_job_psqcatesting'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='showSDC',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='showTesting',
            field=models.BooleanField(default=True),
        ),
    ]
