# Generated by Django 3.2.7 on 2022-01-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0029_auto_20220111_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='pid',
            name='showSDC',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pid',
            name='showTesting',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='showSDC',
            field=models.BooleanField(default=False),
        ),
    ]
