# Generated by Django 3.2.7 on 2021-09-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='GST',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='NTN',
            field=models.CharField(max_length=20),
        ),
    ]
