# Generated by Django 3.2.7 on 2021-09-20 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_rename_jobdate_pid_date'),
        ('refund', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Refund',
            new_name='JobRefund',
        ),
        migrations.CreateModel(
            name='PidRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.IntegerField()),
                ('damageCharges', models.IntegerField()),
                ('washingCharges', models.IntegerField()),
                ('refundAmount', models.IntegerField()),
                ('dueDate', models.DateField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('PIDNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.pid')),
            ],
        ),
    ]
