# Generated by Django 3.2.7 on 2021-09-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refund', '0002_auto_20210920_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobrefund',
            old_name='jobNo',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='pidrefund',
            old_name='PIDNo',
            new_name='pid',
        ),
        migrations.AlterField(
            model_name='jobrefund',
            name='damageCharges',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobrefund',
            name='rent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobrefund',
            name='washingCharges',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pidrefund',
            name='damageCharges',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pidrefund',
            name='rent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pidrefund',
            name='washingCharges',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
