# Generated by Django 3.2.6 on 2021-08-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_lolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
