# Generated by Django 3.2.7 on 2021-09-16 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_shippingline_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lolo',
            old_name='name',
            new_name='lname',
        ),
        migrations.RenameField(
            model_name='lolo',
            old_name='phone',
            new_name='lphone',
        ),
    ]
