# Generated by Django 3.2.7 on 2021-09-16 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20210916_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lolo',
            old_name='lname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='lolo',
            old_name='lphone',
            new_name='phone',
        ),
    ]
