# Generated by Django 3.2.7 on 2021-09-16 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_name_lolo_loloname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='lolo',
            options={'ordering': ['loloname']},
        ),
        migrations.AlterModelOptions(
            name='terminal',
            options={'ordering': ['name']},
        ),
    ]
