# Generated by Django 3.2.7 on 2021-11-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20210916_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingline',
            name='shortname',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
